<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">

    <div>
        <label><?php echo $this->__('Card Type') ?>*</label>
        <span>
            <select name="payment[card_type]" >
                <option value="<?php echo $this->__('ISW') ?>" <?php echo (($this->getInfoData('card_type') == "ISW")? "selected='selected'":""); ?>>
                    <?php echo $this->__('MasterCard/Verve/VISA (Local) Card') ?>
                </option>
                 <option value="<?php echo $this->__('VISIN') ?>" <?php echo (($this->getInfoData('card_type') == "VISIN")? "selected='selected'":""); ?>>
                     <?php echo $this->__('MasterCard/VISA (International) Card') ?>
                 </option>
            </select>

    </span>
    </div>

</div>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>